In [5]:
import numpy as np

rng = np.random.default_rng(seed=42)

a = rng.random(5, )

In [6]:
print(a)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]


In [9]:
print(np.dot(a, a.T))

2.0240041788610026


In [12]:
a = rng.random((5, 1))
print(a)

[[0.37079802]
 [0.92676499]
 [0.64386512]
 [0.82276161]
 [0.4434142 ]]


In [13]:
print(a.T)

[[0.37079802 0.92676499 0.64386512 0.82276161 0.4434142 ]]


In [14]:
print(np.dot(a, a.T))

[[0.13749117 0.34364263 0.23874391 0.30507838 0.16441711]
 [0.34364263 0.85889334 0.59671165 0.76250666 0.41094076]
 [0.23874391 0.59671165 0.41456229 0.5297475  0.28549894]
 [0.30507838 0.76250666 0.5297475  0.67693667 0.36482418]
 [0.16441711 0.41094076 0.28549894 0.36482418 0.19661615]]
